add_library(FreeType INTERFACE IMPORTED)

if(CMAKE_CONFIGURATION_TYPES OR NMAKE)
	target_link_libraries(FreeType INTERFACE optimized "$<BUILD_INTERFACE:${FREETYPE_LIB}>" "$<INSTALL_INTERFACE:@PACKAGE_FREETYPE_INSTALLED_LIB@>")
	target_link_libraries(FreeType INTERFACE debug "$<BUILD_INTERFACE:${FREETYPE_LIB_DBG}>" "$<INSTALL_INTERFACE:@PACKAGE_FREETYPE_INSTALLED_LIB_DBG@>")
else()
	target_link_libraries(FreeType INTERFACE "$<BUILD_INTERFACE:${FREETYPE_LIB}>" "$<INSTALL_INTERFACE:@PACKAGE_FREETYPE_INSTALLED_LIB@>")
endif()